### ISSUE TITLE
Add composer as dependency manager

### ISSUE THREAD

**Issue by wvandenhaak** [xmke/xnova#15]
Would you like to have composer implemented as the dependency manager?

We can use autoloading to move pieces of code to separate classes. 
Maybe it will also be possible to move the Mustache template engine out of the source code so it can be managed by composer.

**Comment by wvandenhaak** [comment]
I already have a branch with composer added to the project. I was also able to remove the Mustache template engine and TinyHTMLMinifier from the codebase (they are now retrieved/managed) with composer 

If you like I can create another PR for this (the code is based on the code from PR #14 )

**Comment by xmke** [comment]
Hi @wvandenhaak,

Thanks for your participation :)

I don't know Composer and how it works,
just give me some time to document myself before :)

I work on XNova on my spare time, sorry for my late responses...

**Comment by wvandenhaak** [comment]
No problem.

Maybe this video can help you getting started which composer:
https://symfonycasts.com/screencast/composer/composer

**Comment by wvandenhaak** [comment]
I see that PR #14 has been merged so this issue can be closed. 
Composer can now be used to install and update the dependencies of this project.

Thanks for merging my pull request.
